spring:
  config:
    import: optional:application-secret.yml
  profiles:
    active: deployment
  jpa:
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        format_sql: true # 실제 디비로 나가는 sql을 보여줌
  sql:
    init:
      mode: always # 애플리케이션 시작 시 스크립트 초기화 (기본값: embedded)