spring:
  datasource:
    url: jdbc:h2:tcp://localhost/~/test-likelion # 메모리 내 데이터베이스 URL, 동시접속을 위해 TCP 모드로 접속
    driver-class-name: org.h2.Driver # H2 드라이버 클래스
    username: sa # 기본 사용자 이름
    password: # 기본 비밀번호
  h2:
    console:
      enabled: true # H2 콘솔을 활성화합니다.
      path: /h2-console # H2 콘솔의 접근 경로
  jpa:
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        format_sql: true # 실제 디비로 나가는 sql을 보여줌
  sql:
    init:
      mode: always # 애플리케이션 시작 시 스크립트 초기화 (기본값: embedded)
  security:
    oauth2:
      client:
        registration:
          google:
            client-id : ${GOOGLE_CLIENT_ID}
            client-secret: ${GOOGLE-CLIENT-SECRET}
            scope:
              - email
              - profile
            redirect-uri: "http://localhost:8080/login/oauth2/code/google"
jwt:
  secret: wgP5RLnvSAn1jYwmQfAj0mN9vFtUjezRUnbpeyFUM80FebMz+jqs38fj5MPOMp2pAL5inafm2c9vtyQP0wxmbHCfuNejCI07m/loW6Qh3trVF1nVL0gX9qfpO7MYDRPeRkaYS7MP4Em4yLPINf0kVfeTBSSWPeZ8YIVsynYMUp3uHX7zIIgvNaoa3JxDvNeeURkDEDqU2/BXvOC0uA28T1qGS1pSMlPSLEvE1bbt70b244r9z0ej9O7G+c/LWzP86pagKY4frWl14O/XaBTav1CzDWwIEFLyhEmz/Is5jGbtW+2dHhetiREJAge9ww+HiQUOqGgdEIBx/s8wBEs3QQ==
